<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="34106" started-at="2017-10-12T15:51:46Z" finished-at="2017-10-12T15:52:20Z">
    <groups>
    </groups>
    <test name="PCS1" duration-ms="34106" started-at="2017-10-12T15:51:46Z" finished-at="2017-10-12T15:52:20Z">
      <class name="getmycourse.CourseEnrol">
        <test-method status="FAIL" signature="enroll(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:getmycourse.CourseEnrol@6ea12c19]" name="enroll" duration-ms="34090" started-at="2017-10-12T11:51:46Z" finished-at="2017-10-12T11:52:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1001110415]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[920940]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[CSC401H1]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[S]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at getmycourse.CourseEnrol.enroll(CourseEnrol.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enroll -->
      </class> <!-- getmycourse.CourseEnrol -->
    </test> <!-- PCS1 -->
  </suite> <!-- Suite -->
</testng-results>
